# Generated by Django 4.2.1 on 2023-05-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruan',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
